/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zhiyou100.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmployeeResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 253396158577062026L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeResult\",\"namespace\":\"com.zhiyou100.entity\",\"fields\":[{\"name\":\"content\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmployeeResult> ENCODER =
      new BinaryMessageEncoder<EmployeeResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmployeeResult> DECODER =
      new BinaryMessageDecoder<EmployeeResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmployeeResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmployeeResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmployeeResult>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmployeeResult to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmployeeResult from a ByteBuffer. */
  public static EmployeeResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence content;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeResult() {}

  /**
   * All-args constructor.
   * @param content The new value for content
   */
  public EmployeeResult(java.lang.CharSequence content) {
    this.content = content;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return content;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: content = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Creates a new EmployeeResult RecordBuilder.
   * @return A new EmployeeResult RecordBuilder
   */
  public static com.zhiyou100.entity.EmployeeResult.Builder newBuilder() {
    return new com.zhiyou100.entity.EmployeeResult.Builder();
  }

  /**
   * Creates a new EmployeeResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeResult RecordBuilder
   */
  public static com.zhiyou100.entity.EmployeeResult.Builder newBuilder(com.zhiyou100.entity.EmployeeResult.Builder other) {
    return new com.zhiyou100.entity.EmployeeResult.Builder(other);
  }

  /**
   * Creates a new EmployeeResult RecordBuilder by copying an existing EmployeeResult instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeResult RecordBuilder
   */
  public static com.zhiyou100.entity.EmployeeResult.Builder newBuilder(com.zhiyou100.entity.EmployeeResult other) {
    return new com.zhiyou100.entity.EmployeeResult.Builder(other);
  }

  /**
   * RecordBuilder for EmployeeResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeResult>
    implements org.apache.avro.data.RecordBuilder<EmployeeResult> {

    private java.lang.CharSequence content;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zhiyou100.entity.EmployeeResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeResult instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zhiyou100.entity.EmployeeResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.zhiyou100.entity.EmployeeResult.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.content = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.zhiyou100.entity.EmployeeResult.Builder clearContent() {
      content = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmployeeResult build() {
      try {
        EmployeeResult record = new EmployeeResult();
        record.content = fieldSetFlags()[0] ? this.content : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmployeeResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmployeeResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmployeeResult>
    READER$ = (org.apache.avro.io.DatumReader<EmployeeResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
